### PR TITLE
Fe 146/implement a welcome page

### PR DESCRIPTION
**Pull request by beyza-akcinar**
Welcome, Sign-Up, Login and Forget Password Pages are added as mentioned in the issues #146 and #148.

### CODE REVIEW

**Comment by HaticeSerraHakyemez** [comment]
I see that welcome, login and register pages are implemented. There doesn't seem to be any problem with your code and I also resolved a simple conflict with the main. With these additions, our frontend now has a solid base. Good work!

**Comment by HaticeSerraHakyemez** [comment]
The code is suitable to merge.

**Review by HaticeSerraHakyemez — APPROVED** [review]
The code is fit to merge.

**Comment by mberkturgut** [comment]
Dear @beyza-akcinar , tremendous work! There is just one issue I realized. The images you used in the welcome page should be put in the project, otherwise it looks like this. A good practice to do it is to create a single folder to include all the images in the project, and use its adress as src. Can you please implement that? 
image

**Comment by mberkturgut** [comment]
@HaticeSerraaHakyemez thanks for detecting the cause and fixing the images!

**Pull request merged**
