### PR TITLE
Create homepage

### PR DESCRIPTION
**Pull request by Alputer**
I created a homepage for our practice-app platform. There is 11 different links to different urls. Currently they contain dummy values, each person will replace the content with their subapplication. Could you check the functionality and the UI of the page?

### CODE REVIEW

**Review by simarahmtkhy — APPROVED** [review]
I have checked the homepage and its functionality. I believe that it is pretty good for the practice app.

**Review by BatuhanIlhan — APPROVED** [review]

**Review by eyusufatik — COMMENTED** [review]
Looks good to me! 👌 

However, we should expand the .gitignore to not include some python files and directories like __pycache__ directories

These are system speccific and should not be included in commits.

So please add a new .gitignore under `practice-app/predictionPoll` ([Python .gitignore](https://github.com/github/gitignore/blob/main/Python.gitignore)) and delete __pycache__ directories from the commits.

**Comment by Alputer** [comment]
I deleted pycache files and updated the gitignore file. I changed gitignore with a more generic version that applies to other cases as well.  The link is [here](https://djangowaves.com/tips-tricks/gitignore-for-a-django-project/)
Could you verify the current version? @eyusufatik

**Comment by eyusufatik** [comment]
looks fine @Alputer

**Review by eyusufatik — APPROVED** [review]

**Pull request merged**
